{{- range $name, $service := .Values.microservices }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: imobill
data:
  application.yml: |
    {{ (.Files.Get "application.yml") | indent 4 }}
{{- end }}
{{- end }}



# helm upgrade --install allianz./allianz--namespace imobill   --set-file application.yml=applicationrepo/config/audit-service-configmap-qa.yaml

