{{- if .Values.global.hpa.enabled }}
{{- range .Values.microservices }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}-hpa
  namespace: imobill
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}-deployment
  minReplicas: {{ $.Values.global.hpa.minReplicas }}
  maxReplicas: {{ $.Values.global.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.global.hpa.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
