{{- range $name, $service := .Values.microservices }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: imobill
data:
  application.yml: |-
{{- if .Values.applicationYml }}
{{ .Values.applicationYml | indent 4 }}
{{- else }}
# applicationYml is NOT set or is empty.
{{- end }}
---
{{- end }}
{{- end }}




# helm upgrade --install einvoice-helmrepo​ ./einvoice-helmrepo​ --namespace imobill   --set-file application.yml=applicationrepo/config/audit-service-configmap-qa.yaml

