{{- range $name, $service := .Values.microservices }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: imobill
data:
  application.yml: |-
{{ $.Values.global.applicationYml | indent 4}}
---
{{- end }}
{{- end }}
