{{- range $name, $service := .Values.microservices }}
{{- if $service.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-deployment
  namespace: imobill
  labels:
    app: {{ $name }}
    environment: {{ $.Values.global.environment }}
spec:
  replicas: {{ $.Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
      environment: {{ $.Values.global.environment }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        environment: {{ $.Values.global.environment }}
    spec:
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ $.Values.global.registry }}/{{ $name }}:{{ $.Values.global.imageTag }}
          ports:
            - containerPort: {{ $service.port }}
          resources:
            requests:
              cpu: {{ $.Values.global.resources.requests.cpu }}
              memory: {{ $.Values.global.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.global.resources.limits.cpu }}
              memory: {{ $.Values.global.resources.limits.memory }}
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: {{ $name }}-config
---
{{- end }}
{{- end }}

{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  namespace: imobill
  labels:
    app: {{ .Values.frontend.name }}
    environment: {{ $.Values.global.environment }}
spec:
  replicas: {{ $.Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      environment: {{ $.Values.global.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        environment: {{ $.Values.global.environment }}
    spec:
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ $.Values.global.registry }}/{{ .Values.frontend.name }}:{{ $.Values.global.imageTag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              cpu: {{ $.Values.global.resources.requests.cpu }}
              memory: {{ $.Values.global.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.global.resources.limits.cpu }}
              memory: {{ $.Values.global.resources.limits.memory }}
---
{{- end }}


{{- if .Values.keycloak.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: {{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
        ports:
        - containerPort: {{ .Values.keycloak.service.port }}
        env:
        {{- range .Values.keycloak.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
          {{- if .valueFrom }}
          valueFrom:
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
          {{- end }}
        {{- end }}
      imagePullSecrets:
      {{- range .Values.keycloak.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
---
{{- end }}

