{{- if .Values.global.hpa.enabled }}
{{- range $name, $service := .Values.microservices }}
{{- if $service.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  namespace: imobill
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}-deployment
  minReplicas: {{ $.Values.global.hpa.minReplicas }}
  maxReplicas: {{ $.Values.global.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.global.hpa.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- end }}

{{- if .Values.frontend.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontend.name }}-hpa
  namespace: imobill
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontend.name }}-deployment
  minReplicas: {{ $.Values.global.hpa.minReplicas }}
  maxReplicas: {{ $.Values.global.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.global.hpa.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- end }}
