global:
  imagePullSecrets:
    - name: my-registry-key-prod
  environment: production
  registry: <prod-aws_account_id>.dkr.ecr.<region>.amazonaws.com #prod-ECR
  replicas: 1
  imageTag: "prod"
  resources:
    requests:
      memory: "2Gb"
      cpu: "2"
    limits:
      memory: "4Gb"
      cpu: "4"
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  configFile: "application.yml"  # Specify the config file for the environment

keycloak:
  enabled: false
  replicas: 1
  image:
    repository: <prod-aws_account_id>.dkr.ecr.<region>.amazonaws.com/keycloak #prod-ECR
    tag: latest
  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
    ports:
      - name: http
        port: 8080
        targetPort: 8080
      - name: https
        port: 8443
        targetPort: 8443
  env:
    KEYCLOAK_ADMIN: "admin"
    KEYCLOAK_ADMIN_PASSWORD: "admin"
    DB_VENDOR: "postgres"
    DB_ADDR: "IP"
    DB_PORT: "Port"
    DB_DATABASE: "db1"
    DB_USER: "DB_USER"
    DB_PASSWORD: "DB_PASSWORD"
  imagePullSecrets:
    - name: my-registry-key-prod

ingress:
  enabled: false
  tlsSecretName: my-tls-secret
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: mydomain.com
