global:
  applicationYml: |-
    ""
  imagePullSecrets:
    - name: my-registry-key
  environment: qa
  registry: <aws_account_id>.dkr.ecr.<region>.amazonaws.com
  replicas: 1
  imageTag: "latest"
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80


keycloak:
  enabled: false
  replicas: 1
  image:
    repository: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/keycloak
    tag: latest
  service:
    type: LoadBalancer
    port: 8443
    targetPort: 8443
    ports:
      - name: https
        port: 8443
        targetPort: 8443
  env:
    - name: DB_VENDOR
      value: "postgres"
    - name: DB_ADDR
      value: "my-db-host"
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: "keycloakdb"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: keycloak-db-credentials
          key: db_keycloak_username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-db-credentials
          key: db_keycloak_password
  imagePullSecrets:
    - name: my-registry-key  # ECR secret key




microservices:
  einvoice-audit-service:
    enabled: false
    port: 8443
  einvoice-bill-gate:
    enabled: false
    port: 8443
  einvoice-category-service:
    enabled: false
    port: 8443
  einvoice-identity-service:
    enabled: false
    port: 8443
  einvoice-increment-service:
    enabled: false
    port: 8443
  einvoice-integration-service:
    enabled: false
    port: 8443
  einvoice-invoice-service:
    enabled: false
    port: 8443
  einvoice-notification-service:
    enabled: false
    port: 8443
  einvoice-pre-sign-service:
    enabled: false
    port: 8443
  einvoice-receive-gate:
    enabled: false
    port: 8443
  einvoice-report-service:
    enabled: false
    port: 8443
  einvoice-searchstatusirbm-service:
    enabled: false
    port: 8443
  einvoice-send-gate:
    enabled: false
    port: 8443
  einvoice-sign-service:
    enabled: false
    port: 8443
  einvoice-xml-service:
    enabled: false
    port: 8443

frontend:
  name: react-frontend
  enabled: false
  port: 80

ingress:
  enabled: false
  tlsSecretName: my-tls-secret
  annotations:
    kubernetes.io/ingress.class: "nginx"
    alb.ingress.kubernetes.io/load-balancer-type: "nlb"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: mydomain.com

